### ISSUE TITLE
Infografia sistemas numericos

### ISSUE THREAD

**Issue by YulianaMorales18** [SistemasTecTlaxiaco/infografia-YulianaMorales18#1]
[Infografia Claudia Yuliana Morales Hernandez 1AS (3).pdf](https://github.com/user-attachments/files/16742310/Infografia.Claudia.Yuliana.Morales.Hernandez.1AS.3.pdf)

**Comment by A-Lorely-Z** [comment]
Redacción y Ortografía: 14/14
Exposición de Ideas Centrales: 14/14
Organización de Ideas Centrales:16/16
Uso de imágenes y colores:14/14
Presentación visual:13/14
Referencias:14/14
Presentación: 14/14
calificación final:19.8/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
